FROM node:22-bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    git \
    lsof \
    && curl -fsSL https://openclaw.ai/install.sh | bash -s -- --no-onboard

ENV NODE_ENV=production

RUN chown -R node:node /usr/local/lib/node_modules/openclaw \
    && chown -R node:node /usr/local/lib/node_modules/npm \
    && chown node:node /usr/local/bin/openclaw /usr/local/bin/npm
